### ISSUE TITLE
I Have Included forge-htmx Into Awesome-Python-HTMX, seeking your feedback

### ISSUE THREAD

**Issue by benjamin-kirkbride** [forgepackages/forge-htmx#17]
A few of us at PyCon this year got together and brainstormed a new Web Stack that we are calling PyHAT (Python, htmx, ASGI, TailwindCSS). The first thing we set out to do is create an "Awesome" collection of active tools/libraries/projects in that space, including yours!

If you could take a look, and also participate in PyHAT-stack/awesome-python-htmx#1 that would be greatly appreciated!

The work you have done seems to be the most mature - by far - of any work done in this space (though I will admit I haven't had a chance to play with it yet). So I'm especially hopefully you will be amicable to getting involved.

**Comment by davegaeddert** [comment]
Thanks @benjamin-kirkbride! Looks like an interesting initiative. I don't have much time to get "involved" right now, but I appreciate the inclusion. I'll definitely keep tabs on some of the discussion there.

**Comment by benjamin-kirkbride** [comment]
@davegaeddert I have to say, your forge tooling all looks great and was in no small part an inspiration for me to undertake this. Thanks for your response!
